kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: thegitopsfridge-web
  namespace: thegitopsfridge
  labels:
    app: thegitopsfridge-web
    app.kubernetes.io/part-of: thegitopsfridge
spec:
  host: thegitopsfridge-web.apps.science-cluster.sandbox2009.opentlc.com
  to:
    kind: Service
    name: thegitopsfridge-app
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
