kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: packoftomatoes
  labels:
    app: packoftomatoes
spec:
  host: packoftomatoes.apps.cluster-9hgj9.9hgj9.sandbox1381.opentlc.com
  to:
    kind: Service
    name: packoftomatoes
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
