apiVersion: apps/v1
kind: Deployment
metadata:
  name: packoftomatoes
  labels:
    app: packoftomatoes
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  replicas: 2
  selector:
    matchLabels:
      app: packoftomatoes
  template:
    metadata:
      labels:
        app: packoftomatoes
    spec:
      containers:
      - name: packoftomatoes
        image: quay.io/mdargatz/thegitopsfridge:v1
        ports:
        - containerPort: 8080