kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: packoftomatoes
  namespace: thegitopsfridge
  labels:
    app: packoftomatoes
spec:
  host: packoftomatoes.apps.science-cluster.sandbox2009.opentlc.com
  to:
    kind: Service
    name: packoftomatoes
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
