apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    path: prereqs/sealed-secrets/apps
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
