apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fillthefridgeright
  namespace: openshift-gitops
spec:
  project: thegitopsfridge
  source:
    path: 00-fillthefridgeright/00a-base
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: topofthefridge
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
