apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: potentiallymoldycompartment
  namespace: openshift-gitops
spec:
  project: thegitopsfridge
  source:
    path: 01-therottenorange/
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: potentially-moldy
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
