apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fingerweg
  namespace: openshift-gitops
spec:
  project: thegitopsfridge
  source:
    path: 02-fingerweg/auth
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: openshift-config
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
