apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fingerweg
spec:
  project: default
  source:
    path: 01-figerweg/auth
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: openshift-config
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
