apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 03a-getstuffout
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: thegitopsfridge
  source:
    path: 03-thefridgeisfull/03a-getstuffout
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: ack-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
