apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 03b-enlargeit
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: thegitopsfridge
  source:
    path: 03-thefridgeisfull/03b-justenlarge
    repoURL: https://github.com/maxisses/thegitopsfridge.git
    targetRevision: main
  destination:
    namespace: openshift-machine-api
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
