apiVersion: apps/v1
kind: Deployment
metadata:
  name: moldyoranges
  labels:
    app: moldyoranges
    app.kubernetes.io/part-of: myfridge
spec:
  replicas: 5
  selector:
    matchLabels:
      app: moldyoranges
  template:
    metadata:
      labels:
        app: moldyoranges
    spec:
      containers:
      - name: moldyoranges
        image: quay.io/mdargatz/thegitopsfridge-orange:v1
        ports:
        - containerPort: 8080