kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: moldyoranges
  namespace: thegitopsfridge
  labels:
    app: moldyoranges
spec:
  host: rottenoranges.apps.science-cluster.sandbox2009.opentlc.com
  to:
    kind: Service
    name: thegitopsfridge-app
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
