kind: OAuth
apiVersion: config.openshift.io/v1
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  identityProviders:
    - name: fridgeusers
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: keepout
    - htpasswd:
        fileData:
          name: scienceusers
      mappingMethod: claim
      name: scienceusers
      type: HTPasswd