apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: NameSpacepotentially-moldy-FullAccess
  namespace: potentially-moldy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete