apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: potentially-moldy-user-access
  namespace: potentially-moldy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: NameSpacepotentially-moldy-FullAccess
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: littlethieve1