apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fullfridge2-user-access
  namespace: potentially-moldy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-fridge2
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dad1
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: parent1
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: parent2