kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-fridge1
  namespace: topofthefridge
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete