apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mypgpassword
  namespace: ack-system
spec:
  encryptedData:
    password: AgAomBC4JpDTpY9s7PI09CQWuH/ms3HoukCf6Hijt8fxwUWfd5vJLA1HEKTw2Ix+Xu2CLiMiIwhvIo73M+yKu4X/QgRbTz4msyS97KC21S9yGL7uGEd6KP21HWQjEYietVPbMsQ2vkZmnwJSA/sFONI81H3vbWMp4z76h/RTuQoecigW50hlEOqy8AQls9k+Diut/cznvUgrLwjtZ1hQW/ytJD74rXZB9YHO+rV5rUaZOlBBFfUdp6zgcp2yGMaFjllCEcUJ/GuAmkHdGiJpP8g/88So3WMyFgeYrcPnrACojsQmy9tOVZedhXWMPpYyJwDOODtUoUuJkThGEh/M05+fWHBzIoAs9gu04yAs/mGm9DhhOgWPbxWWi1ZNsvvfYM1IwoxMQusbiTSV3Rf3sYk0qcHAS6RJscgb47DoAfHa4KsBn9MO6bv/h4fCjE35aGxvl4DkbaVm79VT9FVuZfOUFsdWs57jUC18sK/kgSiVwFBnQubPhSUHQgBkpHaPvWTBMNL43C9Gfx5v4W6rb871VZdNKIYijQ8Zb9F1Kp2M7k5Msdvi2lXz7be8v6j8LPMJcjiFFjsErUOZc1Ncl+Ea5eNnXLVpxPuoPlpmEE5zxY7lpQ4W0tooNG+7dU66lQLVeMYf/nr5koOjE5cD4VNYso4Jid8BT8p3Cf+TlvA4sLE9M6xaFY5jdADj4NcGaVOt7Vi9160=
  template:
    metadata:
      creationTimestamp: null
      name: mypgpassword
      namespace: ack-system
    type: Opaque