apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: k8spgtoaws
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t4g.micro
  dbInstanceIdentifier: k8stopgtoaws
  engine: postgres
  engineVersion: "14"
  masterUsername: postgres
  masterUserPassword:
    namespace: ack-system
    name: mypgpassword
    key: password