apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: movingfromk8stoaws-password
  namespace: sealed-secrets
spec:
  encryptedData:
    password: AgAjXGKuVxJS/geUaBMfbSkqMxhapzuHV7d196YBNkJWWEBvKlkXUKj1Rg0XQIu8z6gNT1Mxomeb2njydqgPQXzI9m7IvjLttxR+iTHtQ4UhevUKLYkgnAZljWqASs6zuw0Pe+aZJCJxLX7SbDw14pTcrTxMoBKfjJsQ8nZjUyZqqijnqhFqzU85B8Gf/ei2I7f6TlNS/VNrec+LPuGevWwye5rL3KdqiUpdmsL9q1kUH9D5xPjNNpUJs0rfuZpDx1Fq5+aHBRLSDIoqJgNUtb/4N7YQVTRdpI1X84GnjMlGrLsQVq2FR/yeTy0qjDgyVQ+Qlaimss6jQfgq4dcZVfg2y/o/UyFO9sI5jWVMQdhzMqFm9KURXnRCnBWFogmLuoeV1OaymhGcK6ZKlQUgpNgp91b6iFK7vlat4qKspULr60lm616pgEStxqcXPvP9EqWi7mgnJzUjrBFFtUpUnUms9cfKID5nbRA3IG48jG/zu1Z92Jc3IT3AG94OVbaCCeQFBWwQBBrFiU5qi64uykwd9nMq8BpOStmxBKnBVUYaOo/+GHhTlGC+vIDY+SHywjqje8wd4zzrdzTcBAtjsmUQZp/k32KZVc7/Qok/HpHwL6Ak7RJyhUBs08piEabmFjs0ezGHGZVXO8ZAoocZUcI19bBcSgla4P5Q3tLgcO0Um6MBoGSQduVADk9yWgkpb5fzif/vOWY=
  template:
    metadata:
      creationTimestamp: null
      name: movingfromk8stoaws-password
      namespace: sealed-secrets
    type: Opaque